apiVersion: apps/v1
kind: Deployment
metadata:
  name: sutro-deployment
spec:
  selector:
    matchLabels:
      app: sutro-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sutro-app
    spec: # Pod specification
      containers:
        - name: sutro-container
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
